<h1 style="color:red">Titanic Passenger Survival Prediction System â€“ Machine Learning Cycle</h1>

# Machine Learning Cycle

### Four phases of a Machine Learning Cycle are

### Training Phase

    Build the Model using Training Data

### Testing Phase

     Evaluate the performance of Model using Testing Data

### Application Phase

     Deploy the Model in the Real-world, to predict Real-time unseen Data

### Feedback Phase

    Take Feedback from the Users and Domain Experts to improve the Model

<h1 style="color:red">Executing Machine Learning Cycle Using a Single File</h1>

# Step 1: Import Libraries

In [3]:
pip install numpy pandas scikit-learn prettytable astropy

Requirement already satisfied: numpy in c:\users\haris ellahi\anaconda3\lib\site-packages (1.23.5)
Requirement already satisfied: pandas in c:\users\haris ellahi\anaconda3\lib\site-packages (1.5.3)
Requirement already satisfied: scikit-learn in c:\users\haris ellahi\anaconda3\lib\site-packages (1.2.1)
Requirement already satisfied: prettytable in c:\users\haris ellahi\anaconda3\lib\site-packages (3.10.2)
Requirement already satisfied: astropy in c:\users\haris ellahi\anaconda3\lib\site-packages (5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\haris ellahi\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\haris ellahi\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\haris ellahi\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: scipy>=1.3.2 in c:\users\haris ellahi\anaconda3\lib\site-packages (from scikit-learn) (1.10.0)
Requirement already satisfied: joblib>=1.1.1 in c:\users\haris ellahi\anaconda3\lib\site-packages (from scikit-learn) (1.1.1)
Requirement already satisfied: wcwidth in c:\users\haris ellahi\anaconda3\lib\site-packages (from prettytable) (0.2.5)
Requirement already satisfied: packaging>=19.0 in c:\users\haris ellahi\anaconda3\lib\site-packages (from astropy) (23.2)
Requirement already satisfied: PyYAML>=3.13 in c:\users\haris ellahi\anaconda3\lib\site-packages (from astropy) (6.0)
Requirement already satisfied: pyerfa>=2.0 in c:\users\haris ellahi\anaconda3\lib\site-packages (from astropy) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\haris ellahi\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
# Import Libraries

import numpy as np
import pandas as pd
import pickle

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn import svm
from sklearn.metrics import accuracy_score

from prettytable import PrettyTable   
from astropy.table import Table, Column

# Step 2: Load Sample Data

In [2]:
# Load Sample Data

sample_data = pd.read_csv("sample-data.csv")

print("\n\nSample Data:")
print("============\n")
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(sample_data)

Sample Data:
============

    PClass  Gender Sibling     Embarked Survived
0    Third    Male     One  Southampton       No
1   Second  Female    Zero  Southampton      Yes
2    Third    Male    Zero  Southampton       No
3    Third  Female   Three  Southampton      Yes
4    Third    Male    Zero   Queenstown       No
5    First  Female   Three  Southampton      Yes
6    Third    Male    Zero  Southampton       No
7    Third    Male    Zero  Southampton      Yes
8    First    Male    Zero  Southampton       No
9   Second    Male    Zero  Southampton      Yes
10   Third    Male     One   Queenstown       No
11   First    Male    Zero    Cherbourg      Yes
12   First    Male    Zero    Cherbourg       No
13  Second  Female    Zero  Southampton      Yes
14  Second    Male    Zero  Southampton       No
15   Third    Male     One    Cherbourg      Yes
16   Third    Male     Two    Cherbourg       No
17   Third    Male    Zero  Southampton      Yes
18   Third    Male    Zero  Southampton       No
19   Third  Female     One    Cherbourg      Yes
20   Third    Male    Zero    Cherbourg       No
21   First  Female    Zero  Southampton      Yes
22   First    Male    Zero    Cherbourg       No
23  Second  Female    Zero  Southampton      Yes
24   Third  Female     One  Southampton       No
25   Third  Female    Zero  Southampton      Yes
26   Third    Male    Zero  Southampton       No
27   Third    Male    Zero  Southampton      Yes
28   Third    Male    Zero  Southampton       No
29   Third  Female     One   Queenstown      Yes
30   Third  Female     Two  Southampton       No
31   First  Female    Zero    Cherbourg      Yes
32   Third    Male     Two  Southampton       No
33   First  Female    Zero  Southampton      Yes
34   First    Male     One    Cherbourg       No
35   First  Female    Zero  Southampton      Yes
36   First    Male     One  Southampton       No
37   Third  Female     One   Queenstown      Yes
38   Third  Female     One  Southampton       No
39  Second  Female     One  Southampton      Yes
40  Second  Female     One  Southampton       No
41   Third  Female    Zero   Queenstown      Yes
42   Third    Male    Zero    Cherbourg       No
43   First  Female    Zero    Cherbourg      Yes
44   Third    Male   Three  Southampton       No
45   Third  Female     One  Southampton      Yes
46   Third    Male    Zero  Southampton       No
47   Third    Male    Zero  Southampton      Yes
48   Third    Male     One  Southampton       No
49  Second  Female    Zero  Southampton      Yes
50   First    Male   Three  Southampton       No
51   Third    Male    Zero  Southampton      Yes
52   Third  Female     One  Southampton       No
53  Second  Female    Zero  Southampton      Yes
54   Third  Female   Three  Southampton       No
55   Third  Female    Zero  Southampton      Yes
56   Third  Female    Zero  Southampton       No
57   Third  Female     One  Southampton      Yes
58   Third    Male    Zero    Cherbourg       No
59   Third    Male    Zero  Southampton      Yes
60  Second    Male    Zero  Southampton       No
61   First  Female     One  Southampton      Yes
62   Third    Male   Three   Queenstown       No
63   Third  Female    Zero   Queenstown      Yes
64  Second  Female    Zero  Southampton       No
65   Third  Female    Zero    Cherbourg      Yes
66   Third    Male    Zero  Southampton       No
67  Second    Male    Zero  Southampton      Yes
68   Third    Male    Zero  Southampton       No
69   First    Male    Zero  Southampton      Yes
70   Third    Male    Zero  Southampton       No
71  Second    Male     Two  Southampton      Yes
72   Third    Male    Zero    Cherbourg       No
73   Third  Female    Zero  Southampton      Yes
74   Third  Female    Zero  Southampton       No
75   First  Female     One  Southampton      Yes
76   Third    Male     One  Southampton       No
77  Second  Female    Zero  Southampton      Yes
78   Third    Male    Zero  Southampton       No
79   Third  Female     Two  Southampton      Yes
80   Third    Male     Two  Southampton       No
81   Third  Female    Zero  Southampton      Yes
82   Third    Male    Zero  Southampton       No
83   First    Male     One  Southampton      Yes
84  Second    Male    Zero  Southampton       No
85   Third  Female     One   Queenstown      Yes
86  Second    Male    Zero  Southampton       No
87   First  Female     One  Southampton      Yes
88   Third    Male    Zero  Southampton       No
89  Second  Female    Zero  Southampton      Yes
90  Second    Male    Zero  Southampton       No
91  Second  Female    Zero  Southampton      Yes
92   Third    Male    Zero    Cherbourg       No
93   First    Male     One  Southampton      Yes
94   First    Male     One  Southampton       No
95   Third    Male     One    Cherbourg      Yes
96   Third    Male     One   Queenstown       No
97   Third    Male     One  Southampton      Yes
98  Second    Male     One  Southampton       No
99   Third    Male     One  Southampton      Yes

# Step 3: Understand and Pre-process Sample Data

## Step 3.1: Understand Sample Data

In [3]:
# Understand Sample Data

print("\n\nAttributes in Sample Data:")
print("==========================\n")

print(sample_data.columns)

print("\n\nNumber of Instances in Sample Data:",sample_data["PClass"].count())
print("========================================\n")

Attributes in Sample Data:
==========================

Index(['PClass', 'Gender', 'Sibling', 'Embarked', 'Survived'], dtype='object')


Number of Instances in Sample Data: 100
========================================

## Step 3.2: Pre-process Sample Data
    o	Sample Data is already Preprocessed
    o	No Preprocessing needs to be Performed

# Step 4: Feature Extraction
    o	Features are already Extracted
    o	No Feature Extraction needs to be Performed

# Step 5: Label Encoding the Sample Data (Input and Output is converted in Numeric Representation)

## Step 5.1: Train the Label Encoder

In [4]:
# Train the Label Encoder
# Labels

pclass = pd.DataFrame({"Pclass":["First","Second","Third"]})
gender = pd.DataFrame({"Gender":["Male","Female"]})
sibling = pd.DataFrame({"Sibling":["Zero","One","Two","Three"]})
embarked = pd.DataFrame({"Embarked":["Southampton","Cherbourg","Queenstown"]})
survived = pd.DataFrame({"Survived":["Yes","No"]})

# Initialize the Label Encoders 

pclass_label_encoder = LabelEncoder()
gender_label_encoder = LabelEncoder()
sibling_label_encoder = LabelEncoder()
embarked_label_encoder = LabelEncoder()
survived_label_encoder = LabelEncoder()

# Train the Label Encoders

pclass_label_encoder.fit(np.ravel(pclass))
gender_label_encoder.fit(np.ravel(gender))
sibling_label_encoder.fit(np.ravel(sibling))
embarked_label_encoder.fit(np.ravel(embarked))
survived_label_encoder.fit(np.ravel(survived))

LabelEncoder()

## Step 5.2: Label Encode the Output

In [5]:
# Label Encoding of the Output

sample_data_encoded_output = sample_data.copy()
original_sample_data = sample_data.copy()

# Transform Output of into Numerical Representation

print("\n\nSurvived Attribute After Label Encoding:")
print("========================================\n")
sample_data["encoded_survived"] = survived_label_encoder.transform(sample_data['Survived'])
print(sample_data[["Survived", "encoded_survived"]])

# Print Original and Encoded Ouput Sample Data

sample_data_encoded_output[['PClass', 'Gender', 'Sibling', 'Embarked', 'Survived']] = sample_data[['PClass', 'Gender', 'Sibling', 'Embarked', 'encoded_survived']]
pd.set_option("display.max_rows", None, "display.max_columns", None)
print("\n\nOriginal Sample Data:")
print("=====================\n")
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(original_sample_data)
print("\n\nSample Data after Label Encoding of Output:")
print("===========================================\n")
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(sample_data_encoded_output)

# Save the Transformed Features into CSV File 

sample_data_encoded_output.to_csv(r'sample-data-encoded-output.csv', index = False, header = True)

Survived Attribute After Label Encoding:
========================================

   Survived  encoded_survived
0        No                 0
1       Yes                 1
2        No                 0
3       Yes                 1
4        No                 0
5       Yes                 1
6        No                 0
7       Yes                 1
8        No                 0
9       Yes                 1
10       No                 0
11      Yes                 1
12       No                 0
13      Yes                 1
14       No                 0
15      Yes                 1
16       No                 0
17      Yes                 1
18       No                 0
19      Yes                 1
20       No                 0
21      Yes                 1
22       No                 0
23      Yes                 1
24       No                 0
25      Yes                 1
26       No                 0
27      Yes                 1
28       No                 0
29      Yes                 1
30       No                 0
31      Yes                 1
32       No                 0
33      Yes                 1
34       No                 0
35      Yes                 1
36       No                 0
37      Yes                 1
38       No                 0
39      Yes                 1
40       No                 0
41      Yes                 1
42       No                 0
43      Yes                 1
44       No                 0
45      Yes                 1
46       No                 0
47      Yes                 1
48       No                 0
49      Yes                 1
50       No                 0
51      Yes                 1
52       No                 0
53      Yes                 1
54       No                 0
55      Yes                 1
56       No                 0
57      Yes                 1
58       No                 0
59      Yes                 1
60       No                 0
61      Yes                 1
62       No                 0
63      Yes                 1
64       No                 0
65      Yes                 1
66       No                 0
67      Yes                 1
68       No                 0
69      Yes                 1
70       No                 0
71      Yes                 1
72       No                 0
73      Yes                 1
74       No                 0
75      Yes                 1
76       No                 0
77      Yes                 1
78       No                 0
79      Yes                 1
80       No                 0
81      Yes                 1
82       No                 0
83      Yes                 1
84       No                 0
85      Yes                 1
86       No                 0
87      Yes                 1
88       No                 0
89      Yes                 1
90       No                 0
91      Yes                 1
92       No                 0
93      Yes                 1
94       No                 0
95      Yes                 1
96       No                 0
97      Yes                 1
98       No                 0
99      Yes                 1


Original Sample Data:
=====================

    PClass  Gender Sibling     Embarked Survived
0    Third    Male     One  Southampton       No
1   Second  Female    Zero  Southampton      Yes
2    Third    Male    Zero  Southampton       No
3    Third  Female   Three  Southampton      Yes
4    Third    Male    Zero   Queenstown       No
5    First  Female   Three  Southampton      Yes
6    Third    Male    Zero  Southampton       No
7    Third    Male    Zero  Southampton      Yes
8    First    Male    Zero  Southampton       No
9   Second    Male    Zero  Southampton      Yes
10   Third    Male     One   Queenstown       No
11   First    Male    Zero    Cherbourg      Yes
12   First    Male    Zero    Cherbourg       No
13  Second  Female    Zero  Southampton      Yes
14  Second    Male    Zero  Southampton       No
15   Third    Male     One    Cherbourg      Yes
16   Third    Male     Two    Cherbourg       No
17   Third    Male    Zero  Southampton      Yes
18   Third    Male    Zero  Southampton       No
19   Third  Female     One    Cherbourg      Yes
20   Third    Male    Zero    Cherbourg       No
21   First  Female    Zero  Southampton      Yes
22   First    Male    Zero    Cherbourg       No
23  Second  Female    Zero  Southampton      Yes
24   Third  Female     One  Southampton       No
25   Third  Female    Zero  Southampton      Yes
26   Third    Male    Zero  Southampton       No
27   Third    Male    Zero  Southampton      Yes
28   Third    Male    Zero  Southampton       No
29   Third  Female     One   Queenstown      Yes
30   Third  Female     Two  Southampton       No
31   First  Female    Zero    Cherbourg      Yes
32   Third    Male     Two  Southampton       No
33   First  Female    Zero  Southampton      Yes
34   First    Male     One    Cherbourg       No
35   First  Female    Zero  Southampton      Yes
36   First    Male     One  Southampton       No
37   Third  Female     One   Queenstown      Yes
38   Third  Female     One  Southampton       No
39  Second  Female     One  Southampton      Yes
40  Second  Female     One  Southampton       No
41   Third  Female    Zero   Queenstown      Yes
42   Third    Male    Zero    Cherbourg       No
43   First  Female    Zero    Cherbourg      Yes
44   Third    Male   Three  Southampton       No
45   Third  Female     One  Southampton      Yes
46   Third    Male    Zero  Southampton       No
47   Third    Male    Zero  Southampton      Yes
48   Third    Male     One  Southampton       No
49  Second  Female    Zero  Southampton      Yes
50   First    Male   Three  Southampton       No
51   Third    Male    Zero  Southampton      Yes
52   Third  Female     One  Southampton       No
53  Second  Female    Zero  Southampton      Yes
54   Third  Female   Three  Southampton       No
55   Third  Female    Zero  Southampton      Yes
56   Third  Female    Zero  Southampton       No
57   Third  Female     One  Southampton      Yes
58   Third    Male    Zero    Cherbourg       No
59   Third    Male    Zero  Southampton      Yes
60  Second    Male    Zero  Southampton       No
61   First  Female     One  Southampton      Yes
62   Third    Male   Three   Queenstown       No
63   Third  Female    Zero   Queenstown      Yes
64  Second  Female    Zero  Southampton       No
65   Third  Female    Zero    Cherbourg      Yes
66   Third    Male    Zero  Southampton       No
67  Second    Male    Zero  Southampton      Yes
68   Third    Male    Zero  Southampton       No
69   First    Male    Zero  Southampton      Yes
70   Third    Male    Zero  Southampton       No
71  Second    Male     Two  Southampton      Yes
72   Third    Male    Zero    Cherbourg       No
73   Third  Female    Zero  Southampton      Yes
74   Third  Female    Zero  Southampton       No
75   First  Female     One  Southampton      Yes
76   Third    Male     One  Southampton       No
77  Second  Female    Zero  Southampton      Yes
78   Third    Male    Zero  Southampton       No
79   Third  Female     Two  Southampton      Yes
80   Third    Male     Two  Southampton       No
81   Third  Female    Zero  Southampton      Yes
82   Third    Male    Zero  Southampton       No
83   First    Male     One  Southampton      Yes
84  Second    Male    Zero  Southampton       No
85   Third  Female     One   Queenstown      Yes
86  Second    Male    Zero  Southampton       No
87   First  Female     One  Southampton      Yes
88   Third    Male    Zero  Southampton       No
89  Second  Female    Zero  Southampton      Yes
90  Second    Male    Zero  Southampton       No
91  Second  Female    Zero  Southampton      Yes
92   Third    Male    Zero    Cherbourg       No
93   First    Male     One  Southampton      Yes
94   First    Male     One  Southampton       No
95   Third    Male     One    Cherbourg      Yes
96   Third    Male     One   Queenstown       No
97   Third    Male     One  Southampton      Yes
98  Second    Male     One  Southampton       No
99   Third    Male     One  Southampton      Yes


Sample Data after Label Encoding of Output:
===========================================

    PClass  Gender Sibling     Embarked  Survived
0    Third    Male     One  Southampton         0
1   Second  Female    Zero  Southampton         1
2    Third    Male    Zero  Southampton         0
3    Third  Female   Three  Southampton         1
4    Third    Male    Zero   Queenstown         0
5    First  Female   Three  Southampton         1
6    Third    Male    Zero  Southampton         0
7    Third    Male    Zero  Southampton         1
8    First    Male    Zero  Southampton         0
9   Second    Male    Zero  Southampton         1
10   Third    Male     One   Queenstown         0
11   First    Male    Zero    Cherbourg         1
12   First    Male    Zero    Cherbourg         0
13  Second  Female    Zero  Southampton         1
14  Second    Male    Zero  Southampton         0
15   Third    Male     One    Cherbourg         1
16   Third    Male     Two    Cherbourg         0
17   Third    Male    Zero  Southampton         1
18   Third    Male    Zero  Southampton         0
19   Third  Female     One    Cherbourg         1
20   Third    Male    Zero    Cherbourg         0
21   First  Female    Zero  Southampton         1
22   First    Male    Zero    Cherbourg         0
23  Second  Female    Zero  Southampton         1
24   Third  Female     One  Southampton         0
25   Third  Female    Zero  Southampton         1
26   Third    Male    Zero  Southampton         0
27   Third    Male    Zero  Southampton         1
28   Third    Male    Zero  Southampton         0
29   Third  Female     One   Queenstown         1
30   Third  Female     Two  Southampton         0
31   First  Female    Zero    Cherbourg         1
32   Third    Male     Two  Southampton         0
33   First  Female    Zero  Southampton         1
34   First    Male     One    Cherbourg         0
35   First  Female    Zero  Southampton         1
36   First    Male     One  Southampton         0
37   Third  Female     One   Queenstown         1
38   Third  Female     One  Southampton         0
39  Second  Female     One  Southampton         1
40  Second  Female     One  Southampton         0
41   Third  Female    Zero   Queenstown         1
42   Third    Male    Zero    Cherbourg         0
43   First  Female    Zero    Cherbourg         1
44   Third    Male   Three  Southampton         0
45   Third  Female     One  Southampton         1
46   Third    Male    Zero  Southampton         0
47   Third    Male    Zero  Southampton         1
48   Third    Male     One  Southampton         0
49  Second  Female    Zero  Southampton         1
50   First    Male   Three  Southampton         0
51   Third    Male    Zero  Southampton         1
52   Third  Female     One  Southampton         0
53  Second  Female    Zero  Southampton         1
54   Third  Female   Three  Southampton         0
55   Third  Female    Zero  Southampton         1
56   Third  Female    Zero  Southampton         0
57   Third  Female     One  Southampton         1
58   Third    Male    Zero    Cherbourg         0
59   Third    Male    Zero  Southampton         1
60  Second    Male    Zero  Southampton         0
61   First  Female     One  Southampton         1
62   Third    Male   Three   Queenstown         0
63   Third  Female    Zero   Queenstown         1
64  Second  Female    Zero  Southampton         0
65   Third  Female    Zero    Cherbourg         1
66   Third    Male    Zero  Southampton         0
67  Second    Male    Zero  Southampton         1
68   Third    Male    Zero  Southampton         0
69   First    Male    Zero  Southampton         1
70   Third    Male    Zero  Southampton         0
71  Second    Male     Two  Southampton         1
72   Third    Male    Zero    Cherbourg         0
73   Third  Female    Zero  Southampton         1
74   Third  Female    Zero  Southampton         0
75   First  Female     One  Southampton         1
76   Third    Male     One  Southampton         0
77  Second  Female    Zero  Southampton         1
78   Third    Male    Zero  Southampton         0
79   Third  Female     Two  Southampton         1
80   Third    Male     Two  Southampton         0
81   Third  Female    Zero  Southampton         1
82   Third    Male    Zero  Southampton         0
83   First    Male     One  Southampton         1
84  Second    Male    Zero  Southampton         0
85   Third  Female     One   Queenstown         1
86  Second    Male    Zero  Southampton         0
87   First  Female     One  Southampton         1
88   Third    Male    Zero  Southampton         0
89  Second  Female    Zero  Southampton         1
90  Second    Male    Zero  Southampton         0
91  Second  Female    Zero  Southampton         1
92   Third    Male    Zero    Cherbourg         0
93   First    Male     One  Southampton         1
94   First    Male     One  Southampton         0
95   Third    Male     One    Cherbourg         1
96   Third    Male     One   Queenstown         0
97   Third    Male     One  Southampton         1
98  Second    Male     One  Southampton         0
99   Third    Male     One  Southampton         1

## Step 5.3: Label Encode the Input

In [6]:
# Label Encoding of the Input

sample_data_encoded = sample_data_encoded_output.copy()
sample_data_encoded_output_orignal = sample_data_encoded_output.copy()

# Transform Input Attributes into Numerical Representation

print("\n\nPClass Attribute After Label Encoding:")
print("======================================\n")
sample_data_encoded_output["encoded_pclass"] = pclass_label_encoder.transform(sample_data_encoded_output['PClass'])
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(sample_data_encoded_output[["PClass", "encoded_pclass"]])

print("\n\nGender Attribute After Label Encoding:")
print("======================================\n")
sample_data_encoded_output["encoded_gender"] = gender_label_encoder.transform(sample_data_encoded_output['Gender'])
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(sample_data_encoded_output[["Gender", "encoded_gender"]])

print("\n\nSibling Attribute After Label Encoding:")
print("=======================================\n")
sample_data_encoded_output["encoded_sibling"] = sibling_label_encoder.transform(sample_data_encoded_output['Sibling'])
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(sample_data_encoded_output[["Sibling", "encoded_sibling"]])

print("\n\nEmbarked Attribute After Label Encoding:")
print("========================================\n")
sample_data_encoded_output["encoded_embarked"] = embarked_label_encoder.transform(sample_data_encoded_output['Embarked'])
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(sample_data_encoded_output[["Embarked", "encoded_embarked"]])

# Print Original and Encoded Sample Data

sample_data_encoded[['PClass', 'Gender', 'Sibling', 'Embarked', 'Survived']] = sample_data_encoded_output[['encoded_pclass', 'encoded_gender', 'encoded_sibling', 'encoded_embarked', 'Survived']]
print("\n\nOriginal Sample Data:")
print("=====================\n")
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(original_sample_data)
print("\n\nSample Data after Label Encoding:")
print("=================================\n")
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(sample_data_encoded)

# Save the Transformed Features into CSV File 

sample_data_encoded.to_csv(r'sample-data-encoded.csv', index = False, header = True)

PClass Attribute After Label Encoding:
======================================

    PClass  encoded_pclass
0    Third               2
1   Second               1
2    Third               2
3    Third               2
4    Third               2
5    First               0
6    Third               2
7    Third               2
8    First               0
9   Second               1
10   Third               2
11   First               0
12   First               0
13  Second               1
14  Second               1
15   Third               2
16   Third               2
17   Third               2
18   Third               2
19   Third               2
20   Third               2
21   First               0
22   First               0
23  Second               1
24   Third               2
25   Third               2
26   Third               2
27   Third               2
28   Third               2
29   Third               2
30   Third               2
31   First               0
32   Third               2
33   First               0
34   First               0
35   First               0
36   First               0
37   Third               2
38   Third               2
39  Second               1
40  Second               1
41   Third               2
42   Third               2
43   First               0
44   Third               2
45   Third               2
46   Third               2
47   Third               2
48   Third               2
49  Second               1
50   First               0
51   Third               2
52   Third               2
53  Second               1
54   Third               2
55   Third               2
56   Third               2
57   Third               2
58   Third               2
59   Third               2
60  Second               1
61   First               0
62   Third               2
63   Third               2
64  Second               1
65   Third               2
66   Third               2
67  Second               1
68   Third               2
69   First               0
70   Third               2
71  Second               1
72   Third               2
73   Third               2
74   Third               2
75   First               0
76   Third               2
77  Second               1
78   Third               2
79   Third               2
80   Third               2
81   Third               2
82   Third               2
83   First               0
84  Second               1
85   Third               2
86  Second               1
87   First               0
88   Third               2
89  Second               1
90  Second               1
91  Second               1
92   Third               2
93   First               0
94   First               0
95   Third               2
96   Third               2
97   Third               2
98  Second               1
99   Third               2


Gender Attribute After Label Encoding:
======================================

    Gender  encoded_gender
0     Male               1
1   Female               0
2     Male               1
3   Female               0
4     Male               1
5   Female               0
6     Male               1
7     Male               1
8     Male               1
9     Male               1
10    Male               1
11    Male               1
12    Male               1
13  Female               0
14    Male               1
15    Male               1
16    Male               1
17    Male               1
18    Male               1
19  Female               0
20    Male               1
21  Female               0
22    Male               1
23  Female               0
24  Female               0
25  Female               0
26    Male               1
27    Male               1
28    Male               1
29  Female               0
30  Female               0
31  Female               0
32    Male               1
33  Female               0
34    Male               1
35  Female               0
36    Male               1
37  Female               0
38  Female               0
39  Female               0
40  Female               0
41  Female               0
42    Male               1
43  Female               0
44    Male               1
45  Female               0
46    Male               1
47    Male               1
48    Male               1
49  Female               0
50    Male               1
51    Male               1
52  Female               0
53  Female               0
54  Female               0
55  Female               0
56  Female               0
57  Female               0
58    Male               1
59    Male               1
60    Male               1
61  Female               0
62    Male               1
63  Female               0
64  Female               0
65  Female               0
66    Male               1
67    Male               1
68    Male               1
69    Male               1
70    Male               1
71    Male               1
72    Male               1
73  Female               0
74  Female               0
75  Female               0
76    Male               1
77  Female               0
78    Male               1
79  Female               0
80    Male               1
81  Female               0
82    Male               1
83    Male               1
84    Male               1
85  Female               0
86    Male               1
87  Female               0
88    Male               1
89  Female               0
90    Male               1
91  Female               0
92    Male               1
93    Male               1
94    Male               1
95    Male               1
96    Male               1
97    Male               1
98    Male               1
99    Male               1


Sibling Attribute After Label Encoding:
=======================================

   Sibling  encoded_sibling
0      One                0
1     Zero                3
2     Zero                3
3    Three                1
4     Zero                3
5    Three                1
6     Zero                3
7     Zero                3
8     Zero                3
9     Zero                3
10     One                0
11    Zero                3
12    Zero                3
13    Zero                3
14    Zero                3
15     One                0
16     Two                2
17    Zero                3
18    Zero                3
19     One                0
20    Zero                3
21    Zero                3
22    Zero                3
23    Zero                3
24     One                0
25    Zero                3
26    Zero                3
27    Zero                3
28    Zero                3
29     One                0
30     Two                2
31    Zero                3
32     Two                2
33    Zero                3
34     One                0
35    Zero                3
36     One                0
37     One                0
38     One                0
39     One                0
40     One                0
41    Zero                3
42    Zero                3
43    Zero                3
44   Three                1
45     One                0
46    Zero                3
47    Zero                3
48     One                0
49    Zero                3
50   Three                1
51    Zero                3
52     One                0
53    Zero                3
54   Three                1
55    Zero                3
56    Zero                3
57     One                0
58    Zero                3
59    Zero                3
60    Zero                3
61     One                0
62   Three                1
63    Zero                3
64    Zero                3
65    Zero                3
66    Zero                3
67    Zero                3
68    Zero                3
69    Zero                3
70    Zero                3
71     Two                2
72    Zero                3
73    Zero                3
74    Zero                3
75     One                0
76     One                0
77    Zero                3
78    Zero                3
79     Two                2
80     Two                2
81    Zero                3
82    Zero                3
83     One                0
84    Zero                3
85     One                0
86    Zero                3
87     One                0
88    Zero                3
89    Zero                3
90    Zero                3
91    Zero                3
92    Zero                3
93     One                0
94     One                0
95     One                0
96     One                0
97     One                0
98     One                0
99     One                0


Embarked Attribute After Label Encoding:
========================================

       Embarked  encoded_embarked
0   Southampton                 2
1   Southampton                 2
2   Southampton                 2
3   Southampton                 2
4    Queenstown                 1
5   Southampton                 2
6   Southampton                 2
7   Southampton                 2
8   Southampton                 2
9   Southampton                 2
10   Queenstown                 1
11    Cherbourg                 0
12    Cherbourg                 0
13  Southampton                 2
14  Southampton                 2
15    Cherbourg                 0
16    Cherbourg                 0
17  Southampton                 2
18  Southampton                 2
19    Cherbourg                 0
20    Cherbourg                 0
21  Southampton                 2
22    Cherbourg                 0
23  Southampton                 2
24  Southampton                 2
25  Southampton                 2
26  Southampton                 2
27  Southampton                 2
28  Southampton                 2
29   Queenstown                 1
30  Southampton                 2
31    Cherbourg                 0
32  Southampton                 2
33  Southampton                 2
34    Cherbourg                 0
35  Southampton                 2
36  Southampton                 2
37   Queenstown                 1
38  Southampton                 2
39  Southampton                 2
40  Southampton                 2
41   Queenstown                 1
42    Cherbourg                 0
43    Cherbourg                 0
44  Southampton                 2
45  Southampton                 2
46  Southampton                 2
47  Southampton                 2
48  Southampton                 2
49  Southampton                 2
50  Southampton                 2
51  Southampton                 2
52  Southampton                 2
53  Southampton                 2
54  Southampton                 2
55  Southampton                 2
56  Southampton                 2
57  Southampton                 2
58    Cherbourg                 0
59  Southampton                 2
60  Southampton                 2
61  Southampton                 2
62   Queenstown                 1
63   Queenstown                 1
64  Southampton                 2
65    Cherbourg                 0
66  Southampton                 2
67  Southampton                 2
68  Southampton                 2
69  Southampton                 2
70  Southampton                 2
71  Southampton                 2
72    Cherbourg                 0
73  Southampton                 2
74  Southampton                 2
75  Southampton                 2
76  Southampton                 2
77  Southampton                 2
78  Southampton                 2
79  Southampton                 2
80  Southampton                 2
81  Southampton                 2
82  Southampton                 2
83  Southampton                 2
84  Southampton                 2
85   Queenstown                 1
86  Southampton                 2
87  Southampton                 2
88  Southampton                 2
89  Southampton                 2
90  Southampton                 2
91  Southampton                 2
92    Cherbourg                 0
93  Southampton                 2
94  Southampton                 2
95    Cherbourg                 0
96   Queenstown                 1
97  Southampton                 2
98  Southampton                 2
99  Southampton                 2


Original Sample Data:
=====================

    PClass  Gender Sibling     Embarked Survived
0    Third    Male     One  Southampton       No
1   Second  Female    Zero  Southampton      Yes
2    Third    Male    Zero  Southampton       No
3    Third  Female   Three  Southampton      Yes
4    Third    Male    Zero   Queenstown       No
5    First  Female   Three  Southampton      Yes
6    Third    Male    Zero  Southampton       No
7    Third    Male    Zero  Southampton      Yes
8    First    Male    Zero  Southampton       No
9   Second    Male    Zero  Southampton      Yes
10   Third    Male     One   Queenstown       No
11   First    Male    Zero    Cherbourg      Yes
12   First    Male    Zero    Cherbourg       No
13  Second  Female    Zero  Southampton      Yes
14  Second    Male    Zero  Southampton       No
15   Third    Male     One    Cherbourg      Yes
16   Third    Male     Two    Cherbourg       No
17   Third    Male    Zero  Southampton      Yes
18   Third    Male    Zero  Southampton       No
19   Third  Female     One    Cherbourg      Yes
20   Third    Male    Zero    Cherbourg       No
21   First  Female    Zero  Southampton      Yes
22   First    Male    Zero    Cherbourg       No
23  Second  Female    Zero  Southampton      Yes
24   Third  Female     One  Southampton       No
25   Third  Female    Zero  Southampton      Yes
26   Third    Male    Zero  Southampton       No
27   Third    Male    Zero  Southampton      Yes
28   Third    Male    Zero  Southampton       No
29   Third  Female     One   Queenstown      Yes
30   Third  Female     Two  Southampton       No
31   First  Female    Zero    Cherbourg      Yes
32   Third    Male     Two  Southampton       No
33   First  Female    Zero  Southampton      Yes
34   First    Male     One    Cherbourg       No
35   First  Female    Zero  Southampton      Yes
36   First    Male     One  Southampton       No
37   Third  Female     One   Queenstown      Yes
38   Third  Female     One  Southampton       No
39  Second  Female     One  Southampton      Yes
40  Second  Female     One  Southampton       No
41   Third  Female    Zero   Queenstown      Yes
42   Third    Male    Zero    Cherbourg       No
43   First  Female    Zero    Cherbourg      Yes
44   Third    Male   Three  Southampton       No
45   Third  Female     One  Southampton      Yes
46   Third    Male    Zero  Southampton       No
47   Third    Male    Zero  Southampton      Yes
48   Third    Male     One  Southampton       No
49  Second  Female    Zero  Southampton      Yes
50   First    Male   Three  Southampton       No
51   Third    Male    Zero  Southampton      Yes
52   Third  Female     One  Southampton       No
53  Second  Female    Zero  Southampton      Yes
54   Third  Female   Three  Southampton       No
55   Third  Female    Zero  Southampton      Yes
56   Third  Female    Zero  Southampton       No
57   Third  Female     One  Southampton      Yes
58   Third    Male    Zero    Cherbourg       No
59   Third    Male    Zero  Southampton      Yes
60  Second    Male    Zero  Southampton       No
61   First  Female     One  Southampton      Yes
62   Third    Male   Three   Queenstown       No
63   Third  Female    Zero   Queenstown      Yes
64  Second  Female    Zero  Southampton       No
65   Third  Female    Zero    Cherbourg      Yes
66   Third    Male    Zero  Southampton       No
67  Second    Male    Zero  Southampton      Yes
68   Third    Male    Zero  Southampton       No
69   First    Male    Zero  Southampton      Yes
70   Third    Male    Zero  Southampton       No
71  Second    Male     Two  Southampton      Yes
72   Third    Male    Zero    Cherbourg       No
73   Third  Female    Zero  Southampton      Yes
74   Third  Female    Zero  Southampton       No
75   First  Female     One  Southampton      Yes
76   Third    Male     One  Southampton       No
77  Second  Female    Zero  Southampton      Yes
78   Third    Male    Zero  Southampton       No
79   Third  Female     Two  Southampton      Yes
80   Third    Male     Two  Southampton       No
81   Third  Female    Zero  Southampton      Yes
82   Third    Male    Zero  Southampton       No
83   First    Male     One  Southampton      Yes
84  Second    Male    Zero  Southampton       No
85   Third  Female     One   Queenstown      Yes
86  Second    Male    Zero  Southampton       No
87   First  Female     One  Southampton      Yes
88   Third    Male    Zero  Southampton       No
89  Second  Female    Zero  Southampton      Yes
90  Second    Male    Zero  Southampton       No
91  Second  Female    Zero  Southampton      Yes
92   Third    Male    Zero    Cherbourg       No
93   First    Male     One  Southampton      Yes
94   First    Male     One  Southampton       No
95   Third    Male     One    Cherbourg      Yes
96   Third    Male     One   Queenstown       No
97   Third    Male     One  Southampton      Yes
98  Second    Male     One  Southampton       No
99   Third    Male     One  Southampton      Yes


Sample Data after Label Encoding:
=================================

    PClass  Gender  Sibling  Embarked  Survived
0        2       1        0         2         0
1        1       0        3         2         1
2        2       1        3         2         0
3        2       0        1         2         1
4        2       1        3         1         0
5        0       0        1         2         1
6        2       1        3         2         0
7        2       1        3         2         1
8        0       1        3         2         0
9        1       1        3         2         1
10       2       1        0         1         0
11       0       1        3         0         1
12       0       1        3         0         0
13       1       0        3         2         1
14       1       1        3         2         0
15       2       1        0         0         1
16       2       1        2         0         0
17       2       1        3         2         1
18       2       1        3         2         0
19       2       0        0         0         1
20       2       1        3         0         0
21       0       0        3         2         1
22       0       1        3         0         0
23       1       0        3         2         1
24       2       0        0         2         0
25       2       0        3         2         1
26       2       1        3         2         0
27       2       1        3         2         1
28       2       1        3         2         0
29       2       0        0         1         1
30       2       0        2         2         0
31       0       0        3         0         1
32       2       1        2         2         0
33       0       0        3         2         1
34       0       1        0         0         0
35       0       0        3         2         1
36       0       1        0         2         0
37       2       0        0         1         1
38       2       0        0         2         0
39       1       0        0         2         1
40       1       0        0         2         0
41       2       0        3         1         1
42       2       1        3         0         0
43       0       0        3         0         1
44       2       1        1         2         0
45       2       0        0         2         1
46       2       1        3         2         0
47       2       1        3         2         1
48       2       1        0         2         0
49       1       0        3         2         1
50       0       1        1         2         0
51       2       1        3         2         1
52       2       0        0         2         0
53       1       0        3         2         1
54       2       0        1         2         0
55       2       0        3         2         1
56       2       0        3         2         0
57       2       0        0         2         1
58       2       1        3         0         0

# Step 6: Execute the Training Phase

## Step 6.1: Splitting Sample Data into Training Data and Testing Data

In [7]:
# Splitting Sample Data into Training Data and Testing Data

training_data_encoded, testing_data_encoded = train_test_split( sample_data_encoded , test_size=0.2 , random_state=0 , shuffle = False)

# Save the Training and Testing Data into CSV File 

training_data_encoded.to_csv(r'training-data-encoded.csv', index = False, header = True)
testing_data_encoded.to_csv(r'testing-data-encoded.csv', index = False, header = True)

# print Training and Testing Data

print("\n\nTraining Data:")
print("==============\n")
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(training_data_encoded)
print("\n\nTesting Data:")
print("==============\n")
pd.set_option("display.max_rows", None, "display.max_columns", None)
print(testing_data_encoded)

Training Data:
==============

    PClass  Gender  Sibling  Embarked  Survived
0        2       1        0         2         0
1        1       0        3         2         1
2        2       1        3         2         0
3        2       0        1         2         1
4        2       1        3         1         0
5        0       0        1         2         1
6        2       1        3         2         0
7        2       1        3         2         1
8        0       1        3         2         0
9        1       1        3         2         1
10       2       1        0         1         0
11       0       1        3         0         1
12       0       1        3         0         0
13       1       0        3         2         1
14       1       1        3         2         0
15       2       1        0         0         1
16       2       1        2         0         0
17       2       1        3         2         1
18       2       1        3         2         0
19       2       0        0         0         1
20       2       1        3         0         0
21       0       0        3         2         1
22       0       1        3         0         0
23       1       0        3         2         1
24       2       0        0         2         0
25       2       0        3         2         1
26       2       1        3         2         0
27       2       1        3         2         1
28       2       1        3         2         0
29       2       0        0         1         1
30       2       0        2         2         0
31       0       0        3         0         1
32       2       1        2         2         0
33       0       0        3         2         1
34       0       1        0         0         0
35       0       0        3         2         1
36       0       1        0         2         0
37       2       0        0         1         1
38       2       0        0         2         0
39       1       0        0         2         1
40       1       0        0         2         0
41       2       0        3         1         1
42       2       1        3         0         0
43       0       0        3         0         1
44       2       1        1         2         0
45       2       0        0         2         1
46       2       1        3         2         0
47       2       1        3         2         1
48       2       1        0         2         0
49       1       0        3         2         1
50       0       1        1         2         0
51       2       1        3         2         1
52       2       0        0         2         0
53       1       0        3         2         1
54       2       0        1         2         0
55       2       0        3         2         1
56       2       0        3         2         0
57       2       0        0         2         1
58       2       1        3         0         0
59       2       1        3         2         1
60       1       1        3         2         0
61       0       0        0         2         1
62       2       1        1         1         0
63       2       0        3         1         1
64       1       0        3         2         0
65       2       0        3         0         1
66       2       1        3         2         0
67       1       1        3         2         1
68       2       1        3         2         0
69       0       1        3         2         1
70       2       1        3         2         0
71       1       1        2         2         1
72       2       1        3         0         0
73       2       0        3         2         1
74       2       0        3         2         0
75       0       0        0         2         1
76       2       1        0         2         0
77       1       0        3         2         1
78       2       1        3         2         0
79       2       0        2         2         1


Testing Data:
==============

    PClass  Gender  Sibling  Embarked  Survived
80       2       1        2         2         0
81       2       0        3         2         1
82       2       1        3         2         0
83       0       1        0         2         1
84       1       1        3         2         0
85       2       0        0         1         1
86       1       1        3         2         0
87       0       0        0         2         1
88       2       1        3         2         0
89       1       0        3         2         1
90       1       1        3         2         0
91       1       0        3         2         1
92       2       1        3         0         0
93       0       1        0         2         1
94       0       1        0         2         0
95       2       1        0         0         1
96       2       1        0         1         0
97       2       1        0         2         1
98       1       1        0         2         0
99       2       1        0         2         1

## Step 6.2: Splitting Input Vectors and Outputs / Labels of Training Data

In [8]:
# Splitting Input Vectors and Outputs / Labels of Training Data


print("\n\nInputs Vectors (Feature Vectors) of Training Data:")
print("==================================================\n")
input_vector_train = training_data_encoded.iloc[: , :-1]
print(input_vector_train)

print("\n\nOutputs/Labels of Training Data:")
print("================================\n")
print("  Survived")
output_label_train = training_data_encoded.iloc[: ,-1]
print(output_label_train)

Inputs Vectors (Feature Vectors) of Training Data:
==================================================

    PClass  Gender  Sibling  Embarked
0        2       1        0         2
1        1       0        3         2
2        2       1        3         2
3        2       0        1         2
4        2       1        3         1
5        0       0        1         2
6        2       1        3         2
7        2       1        3         2
8        0       1        3         2
9        1       1        3         2
10       2       1        0         1
11       0       1        3         0
12       0       1        3         0
13       1       0        3         2
14       1       1        3         2
15       2       1        0         0
16       2       1        2         0
17       2       1        3         2
18       2       1        3         2
19       2       0        0         0
20       2       1        3         0
21       0       0        3         2
22       0       1        3         0
23       1       0        3         2
24       2       0        0         2
25       2       0        3         2
26       2       1        3         2
27       2       1        3         2
28       2       1        3         2
29       2       0        0         1
30       2       0        2         2
31       0       0        3         0
32       2       1        2         2
33       0       0        3         2
34       0       1        0         0
35       0       0        3         2
36       0       1        0         2
37       2       0        0         1
38       2       0        0         2
39       1       0        0         2
40       1       0        0         2
41       2       0        3         1
42       2       1        3         0
43       0       0        3         0
44       2       1        1         2
45       2       0        0         2
46       2       1        3         2
47       2       1        3         2
48       2       1        0         2
49       1       0        3         2
50       0       1        1         2
51       2       1        3         2
52       2       0        0         2
53       1       0        3         2
54       2       0        1         2
55       2       0        3         2
56       2       0        3         2
57       2       0        0         2
58       2       1        3         0
59       2       1        3         2
60       1       1        3         2
61       0       0        0         2
62       2       1        1         1
63       2       0        3         1
64       1       0        3         2
65       2       0        3         0
66       2       1        3         2
67       1       1        3         2
68       2       1        3         2
69       0       1        3         2
70       2       1        3         2
71       1       1        2         2
72       2       1        3         0
73       2       0        3         2
74       2       0        3         2
75       0       0        0         2
76       2       1        0         2
77       1       0        3         2
78       2       1        3         2
79       2       0        2         2


Outputs/Labels of Training Data:
================================

  Survived
0     0
1     1
2     0
3     1
4     0
5     1
6     0
7     1
8     0
9     1
10    0
11    1
12    0
13    1
14    0
15    1
16    0
17    1
18    0
19    1
20    0
21    1
22    0
23    1
24    0
25    1
26    0
27    1
28    0
29    1
30    0
31    1
32    0
33    1
34    0
35    1
36    0
37    1
38    0
39    1
40    0
41    1
42    0
43    1
44    0
45    1
46    0
47    1
48    0
49    1
50    0
51    1
52    0
53    1
54    0
55    1
56    0
57    1
58    0
59    1
60    0
61    1
62    0
63    1
64    0
65    1
66    0
67    1
68    0
69    1
70    0
71    1
72    0
73    1
74    0
75    1
76    0
77    1
78    0
79    1
Name: Survived, dtype: int32

## 6.3: Train the Support Vector Classifier

In [9]:
# Train the Support Vector Classifier

print("\n\nTraining the Support Vector Classifier on Training Data")
print("========================================================\n")
print("\nParameters and their values:")
print("============================\n")
svc_model = svm.SVC(gamma='auto',random_state=0)
svc_model.fit(input_vector_train,np.ravel(output_label_train))
print(svc_model)

Training the Support Vector Classifier on Training Data
========================================================


Parameters and their values:
============================

SVC(gamma='auto', random_state=0)

## Step 6.4: Save the Trained Model

In [10]:
# Save the Trained Model

# Save the Model in a Pkl File

pickle.dump(svc_model, open('svc_trained_model.pkl', 'wb'))

# Step 7: Execute the Testing Phase

## Step 7.1: Splitting Input Vectors and Outputs/Labels of Testing Data

In [11]:
# Splitting Input Vectors and Outputs/Labels of Testing Data
print("\n\nInputs Vectors (Feature Vectors) of Testing Data:")
print("=================================================\n")
input_vector_test = testing_data_encoded.iloc[: , :-1]
print(input_vector_test)

print("\n\nOutputs/Labels of Testing Data:")
print("==============================\n")
print("  Survived")
output_label_test = testing_data_encoded.iloc[: ,-1]
print(output_label_test)

Inputs Vectors (Feature Vectors) of Testing Data:
=================================================

    PClass  Gender  Sibling  Embarked
80       2       1        2         2
81       2       0        3         2
82       2       1        3         2
83       0       1        0         2
84       1       1        3         2
85       2       0        0         1
86       1       1        3         2
87       0       0        0         2
88       2       1        3         2
89       1       0        3         2
90       1       1        3         2
91       1       0        3         2
92       2       1        3         0
93       0       1        0         2
94       0       1        0         2
95       2       1        0         0
96       2       1        0         1
97       2       1        0         2
98       1       1        0         2
99       2       1        0         2


Outputs/Labels of Testing Data:
==============================

  Survived
80    0
81    1
82    0
83    1
84    0
85    1
86    0
87    1
88    0
89    1
90    0
91    1
92    0
93    1
94    0
95    1
96    0
97    1
98    0
99    1
Name: Survived, dtype: int32

## Step 7.2: Load the Saved Model

In [12]:
# Load the Saved Model
# Load the Saved Model

model = pickle.load(open('svc_trained_model.pkl', 'rb'))

## Step 7.3: Evaluate the Machine Learning Model
### Step 7.3.1: Make Predictions with the Trained Models on Testing Data

In [13]:
# Evaluate the Machine Learning Model

# Provide Test data to the Trained Model

model_predictions = model.predict(input_vector_test)
testing_data_encoded.copy(deep=True)
pd.options.mode.chained_assignment = None
testing_data_encoded["Predictions"] = model_predictions

# Save the Predictions into CSV File

testing_data_encoded.to_csv(r'model-predictions.csv', index = False, header = True)

model_predictions = testing_data_encoded 
print("\n\nPredictions Returned by svc_trained_model:")
print("==========================================\n")
print(model_predictions)

Predictions Returned by svc_trained_model:
==========================================

    PClass  Gender  Sibling  Embarked  Survived  Predictions
80       2       1        2         2         0            0
81       2       0        3         2         1            1
82       2       1        3         2         0            0
83       0       1        0         2         1            0
84       1       1        3         2         0            0
85       2       0        0         1         1            1
86       1       1        3         2         0            0
87       0       0        0         2         1            1
88       2       1        3         2         0            0
89       1       0        3         2         1            1
90       1       1        3         2         0            0
91       1       0        3         2         1            1
92       2       1        3         0         0            0
93       0       1        0         2         1            0
94       0       1        0         2         0            0
95       2       1        0         0         1            1
96       2       1        0         1         0            0
97       2       1        0         2         1            0
98       1       1        0         2         0            0
99       2       1        0         2         1            0

## Step 7.4: Calculate the Accuracy Score

In [14]:
# Calculate the Accuracy Score

# Calculate the Accuracy

model_accuracy_score = accuracy_score(model_predictions["Survived"],model_predictions["Predictions"])

print("\n\nAccuracy Score:")
print("===============\n")
print(round(model_accuracy_score,2))

Accuracy Score:
===============

0.8

# Step 8: Execute the Application Phase

## Step 8.1: Take Input from User

In [16]:
# Take Input from User

pclass_input = input("\nPlease enter PClass here (First,Second,Third) : ").strip()
gender_input = input("\nPlease enter your Gender here (Male, Female) : ").strip()
sibling_input = input("\nPlease enter your Sibling here (Zero,One,Two,Three) : ").strip()
embarked_input = input("\nPlease enter Embarked here (Cherbourg,Southampton,Queenstown) : ").strip()

Please enter PClass here (First,Second,Third) : Second

Please enter your Gender here (Male, Female) : Male

Please enter your Sibling here (Zero,One,Two,Three) : One

Please enter Embarked here (Cherbourg,Southampton,Queenstown) : Southampton

## Step 8.2: Convert User Input into Feature Vector (Exactly Same as Feature Vectors of Sample Data)

In [17]:
# Convert User Input into Feature Vector

user_input = pd.DataFrame({ 'PClass': [pclass_input],'Gender': [gender_input],'Sibling': [sibling_input],'Embarked': [embarked_input]})

print("\n\nUser Input Feature Vector:")
print("==========================\n")
print(user_input)

User Input Feature Vector:
==========================

   PClass Gender Sibling     Embarked
0  Second   Male     One  Southampton

## Step 8.3: Label Encoding of Feature Vector (Exactly Same as Label Encoded Feature Vectors of Sample Data)

In [18]:
# Label Encoding

# Transform Input (Categorical) Attributes of Unseen Data into Numerical Representation

unseen_data_features = user_input.copy()
unseen_data_features["PClass"] = pclass_label_encoder.transform(user_input['PClass'])
unseen_data_features["Gender"] = gender_label_encoder.transform(user_input['Gender'])
unseen_data_features["Sibling"] = sibling_label_encoder.transform(user_input['Sibling'])
unseen_data_features["Embarked"] = embarked_label_encoder.transform(user_input['Embarked'])

print("\n\nUser Input Feature Vector:")
print("==========================\n")
print(user_input)

print("\n\nUser Input Encoded Feature Vector:")
print("==================================\n")
print(unseen_data_features)

User Input Feature Vector:
==========================

   PClass Gender Sibling     Embarked
0  Second   Male     One  Southampton


User Input Encoded Feature Vector:
==================================

   PClass  Gender  Sibling  Embarked
0       1       1        0         2

## Step 8.4: Load the Saved Model

In [19]:
# Load the Saved Model

# Load the Saved Model

model = pickle.load(open('svc_trained_model.pkl', 'rb'))

## Step 8.5: Model Prediction
### Step 8.5.1: Apply Model on the Label Encoded Feature Vector of unseen instance and return Prediction to the User

In [20]:
# Prediction of Unseen Instance

# Make a Prediction on Unseen Data

predicted_survival = model.predict(unseen_data_features)

if(predicted_survival == 1): 
    prediction = "SURVIVED"
if(predicted_survival == 0):
    prediction = "NOT SURVIVED"

# Add the Prediction in a Pretty Table

pretty_table = PrettyTable()
pretty_table.add_column("       ** Prediction **       ",[prediction])
print(pretty_table)

+--------------------------------+
|        ** Prediction **        |
+--------------------------------+
|          NOT SURVIVED          |
+--------------------------------+

# Step 9: Execute the Feedback Phase
## A Two-Step Process
### Step 01: After some time, take Feedback from
    o	Domain Experts and Users on deployed Titanic Passenger Survival Prediction System
### Step 02: Make a List of Possible Improvements based on Feedback received

# Step 10: Improve Model based on Feedback
### There is Always Room for Improvement
### Based on Feedback from Domain Experts and Users
    o	Improve your Model